template1: template1.cc
	g++ -g -std=c++11 template1.cc -o template1

.PHONY: clean template2 template3

template2:
	g++ -g -std=c++11 template2.cc -o template2

template3:
	g++ -g template3.cc -o template3

my_vector:
	g++ -g my_vector.cc -o my_vector

clean:
	rm -rf template1 template2